name: black_pearl
description: BlackPearlMobileApp


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  auto_route:
  flutter_riverpod: ^2.0.2
  riverpod_annotation: ^1.0.4
  table_calendar: ^3.0.3
  after_layout: ^1.1.0
  provider: ^6.0.4
  firebase_auth:
  cloud_firestore:
  firebase_database: ^9.0.5
  flutter_datetime_picker: ^1.5.1
  flutter_dropzone: ^3.0.5
  date_format: ^2.0.5
  cloud_functions:
  firebase_helpers: ^0.5.0
  firebase_core:
  firebase_storage:
  image_picker:
  flutter:
    sdk: flutter

  package_info:
  google_sign_in:
  device_info:
  cupertino_icons: ^1.0.2
  flutter_hooks: ^0.18.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner:
  auto_route_generator:
  riverpod_generator: ^1.0.4

flutter:

  uses-material-design: true

  assets:
    - assets/Football_field.svg.png
    - assets/piessa.jpg
  fonts:
    - family: inconsolata
      fonts:
        - asset: fonts/Inconsolata/Inconsolata-VariableFont_wdth,wght.ttf

